name: matrix test

on:
  push:
  workflow_dispatch:
    inputs:
      x:
        definition:
        type: string

jobs:
  my_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        x: ['a', 'b', 'c']
        y: ['1', '2', '3']
        include:
          - x: ${{ fromJson(github.event.inputs.x) }}
            y: ${{ fromJson(github.event.inputs.y) }}
    steps:
      - run: |
          echo "${{matrix.x}}${{matrix.y}}"
