name: matrix test

env:
  X_VALS: "['a','b','c']"
  Y_VALS: "['1','2','3']"

on:
  push:
  workflow_dispatch:
    inputs:
      x:
        description: manual override for x
        type: choice
        # manually keep the options in sync with X_VALS
        options: 
          - 'a'
          - 'b'
          - 'c'
      y:
        description: manual override for y
        type: choice
        # manually keep the options in sync with Y_VALS
        options: 
          - '1'
          - '2'
          - '3'

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      X_IN: ${{ github.event.inputs.x }}
      y_IN: ${{ github.event.inputs.y }}
    steps:
      - id: set-matrix
        run: |
          if [ -z ${X_IN} ]; then
            echo "::set-output name=x::${X_VALS}]"
          else
            echo "::set-output name=x::['${X_IN}']"
          fi

          # set y to Y_VALS if no input was provided
          if [ -z ${Y_IN} ]; then
            echo "::set-output name=y::${Y_VALS}"
          else
            echo "::set-output name=y::['${Y_IN}']"
          fi
    outputs:
      x: ${{ steps.set-matrix.outputs.x }}
      y: ${{ steps.set-matrix.outputs.y }}
  my_job:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        x: ${{ fromJSON(needs.setup.outputs.x) }}
        y: ${{ fromJSON(needs.setup.outputs.y) }}
    steps:
      - run: echo ${{matrix.x}}${{matrix.y}}
