# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      x:
        description: manual input for x
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        x: ['1', '2', ${{ github.event.inputs.x }}]
      fail-fast: false
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - run: |
          echo x is ${{matrix.release}}
