# This is a basic workflow to help you get started with Actions

name: matrix test

# Controls when the action will run.
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      x:
        description: manual input for x
        type: string
      y:
        description: manual input for y
        type: string

jobs:
  my_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        x: ['a', 'b', 'c']
        y: ['1', '2', '3']
    steps:
      - run: |
          echo "${{matrix.x}}${{matrix.y}}"
