name: matrix test

on:
  push:

jobs:
  my_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        x: ['a', 'b', 'c']
        y: ['1', '2', '3']
        include:
          - x: 'd'
    steps:
      - run: |
          echo "${{matrix.x}}${{matrix.y}}"
